INSERT IGNORE INTO PRODUTORA(id, nome,data_fundacao) values(1,'Rockstar Games','1998-12-01') ;
INSERT IGNORE INTO PRODUTORA(id, nome,data_fundacao) values(2,'Ubisoft','1986-05-12') ;
INSERT IGNORE INTO PRODUTORA(id, nome,data_fundacao) values(3,'Epic Games','1991-01-15') ;
INSERT IGNORE INTO PRODUTORA(id, nome,data_fundacao) values(4,'Electronic Arts','1982-05-27') ;


INSERT IGNORE INTO PUBLICACAO(ID, DATA_PUBLICACAO, TITULO, DESCRICAO) values(1,'2021-08-26','ULTIMO POST', 'POST TESTE 3') ;
INSERT IGNORE INTO PUBLICACAO(ID, DATA_PUBLICACAO, TITULO, DESCRICAO) values(2,'2021-08-27','POST DO MEIO', 'POST TESTE 2') ;
INSERT IGNORE INTO PUBLICACAO(ID, DATA_PUBLICACAO, TITULO, DESCRICAO) values(3,'2021-09-02','PRIMEIRO POST', 'POST TESTE 1') ;